### PR TITLE
Perform direct https requests instead of going through headless chrome

### PR DESCRIPTION
**Pull request by ZJONSSON**
ASP servers usually require a two pass approach, first to pick up VIEWSTATE etc that is then passed into the actual request for information.   Here is an implementation using `request` directly from node.js.  Feel free to merge or cherry pick if you find it useful.

### CODE REVIEW

**Comment by kristjanmik** [comment]
I'm not lying when I say it but this is the best PR since sliced bread. Not sure how I completely missed this approach. This makes the scraper super fast!!!

**Comment by kristjanmik** [comment]
Thanks for an awesome contribution @ZJONSSON, it will save voters in Iceland few days in waiting times :P

**Comment by kristjanmik** [comment]
Pushed this code to production 🎉

**Comment by ZJONSSON** [comment]
Excellent!  Glad I could be of help!

**Pull request merged**
